name: 'Report Julia CI results'
description: 'Report Julia CI results'
inputs:
  results-path:
    type: string
    required: true
  lint-results:
    required: false
runs:
  using: "composite"
  steps:
    - name: Install and precompile
      run: julia -e 'import Pkg; Pkg.instantiate()'
      shell: bash
      env:
        JULIA_PROJECT: ${{ github.action_path }}
    - name: Report results
      run: julia --project=${{ github.action_path }} ${{ github.action_path }}/main.jl
      shell: pwsh
      env:
        RESULTS_PATH: ${{ inputs.results-path }}
        LINT_RESULTS: ${{ inputs.lint-results }}
